# Generated by Django 5.1.6 on 2025-02-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'verbose_name': 'Problem', 'verbose_name_plural': 'Problems'},
        ),
        migrations.AddField(
            model_name='problem',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='problem',
            name='option_a',
            field=models.CharField(default='Option A', max_length=255),
        ),
        migrations.AddField(
            model_name='problem',
            name='option_b',
            field=models.CharField(default='Option B', max_length=255),
        ),
        migrations.AddField(
            model_name='problem',
            name='option_c',
            field=models.CharField(default='Option C', max_length=255),
        ),
        migrations.AddField(
            model_name='problem',
            name='option_d',
            field=models.CharField(default='Option D', max_length=255),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.TextField(default='No solution provided'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=6),
        ),
    ]
