# Generated by Django 5.1.6 on 2025-02-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_problem_options_problem_correct_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solutions',
            field=models.TextField(default='No solutions provided'),
        ),
    ]
