# Generated by Django 5.1.6 on 2025-02-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='options',
            field=models.TextField(default='No options provided'),
        ),
    ]
