# Generated by Django 5.1.6 on 2025-02-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_remove_problem_options_remove_problem_solutions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='solution',
            new_name='solutions',
        ),
    ]
