# Generated by Django 5.1.4 on 2025-02-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussionform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
