# Generated by Django 5.1.6 on 2025-02-15 10:09

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='profile_pictures/default.jpeg', upload_to=users.models.user_profile_picture_path),
        ),
    ]
